steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.video', '-t', 'gcr.io/vaultbot-486713/vaultbot-video-worker', '.']
images:
- 'gcr.io/vaultbot-486713/vaultbot-video-worker'
timeout: 1200s
