steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.image', '-t', 'gcr.io/vaultbot-486713/vaultbot-image-worker', '.']
images:
- 'gcr.io/vaultbot-486713/vaultbot-image-worker'
timeout: 1200s
